### ISSUE TITLE
Sandstorm.

### ISSUE THREAD

**Issue by kodbilenadam** [WatchBeam/emoticons#22]
Dududududududududududu. 

:dudu or :witnots (what is the name of the song) or :duDudu. 

A sand storm emote could be really nice. 

You know what I mean. Dudududududu :3

**Comment by MattJustMatt** [comment]
What would this look like?

**Comment by QuirkySquid** [comment]
Bad art is bad, but here's a random sandstorm: ![sandstorm](https://cloud.githubusercontent.com/assets/15622691/13373691/8b23b216-dd3c-11e5-9ed2-624abfa59e42.png)

**Comment by 2Cubed** [comment]
:+1:

**Comment by kodbilenadam** [comment]
@QuirkySquid This one is good but it looks like only desert with some sand but i liked it. 

I will try to convert this one into an icon:
![Sandstorm](http://vignette3.wikia.nocookie.net/naruto/images/9/96/Sandstorm_Technique.png/revision/latest?cb=20150501091013)

**Comment by ImNatho** [comment]
PR #27 has a sandstorm icon in it

**Comment by kodbilenadam** [comment]
We have it on pull #28 come on @MattJustMatt

**Comment by ImNatho** [comment]
Haha. The first PR I made didn't pass the tests on Travis for some reason? I closed it and made a new one and it worked just fine lol :P

**Comment by kodbilenadam** [comment]
@ImNatho Thanks for that but still waiting for someone to add that on Beam :(

**Comment by ImNatho** [comment]
@kodbilenadam It's only like 4 hours old :toilet:

**Comment by kodbilenadam** [comment]
@ImNatho Also 20 days old :(

**Comment by MattJustMatt** [comment]
Sorry but we don't have plans to add this emote at this time. It's pretty difficult to make a sandstorm emote!
